public class Customer {

    //CONSOLE APPLICATION DOVREBBE AGGIUNGERE IL RIFERIMENTO ALLA CLASSE
    //CLICK DESTRO, REFERENCE SULLA CLASSE A CUI SIAMO INTERESSATI AGGIUNGERE IL
    //RIFERIMENTO AD UNA LIBRERIA, AGGIUNGI, RIFERIMENTO PROGETTO, OK
    public int customerID;
    public string customerName;
}
